### PR TITLE
In recent versions of libpqxx the pqxx::prepare::treat_string has been removed.

### PR DESCRIPTION
**Pull request by skinkie**
Please validate this code works as expected.

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by kinnou02** [comment]
ok to test.

**Comment by kinnou02** [comment]
Same problem as with zmq, it's builds with pqxx 3 but doesn't works:

```
Too many arguments for prepared statement messages: expected 0, received 2
```

**Comment by antoine-de** [comment]
This PR cannot be merged 'as is' for the moment because we need a more complex patch to handle the 2 different versions of pqxx (the are unfortunatly not compatible...).

We'll work on that a soon as possible, thanks again @skinkie !

**Pull request closed without merging**
