### PR TITLE
Doc: migration to riot in license headers

### PR DESCRIPTION
**Pull request by kinnou02**
thanks to ```sed -i -e 's@IRC #navitia on freenode@channel `#navitia` on riot 
 https://riot.im/app/#/room/#navitia:matrix.org@'```

### CODE REVIEW

**Review by benoit-bst — APPROVED** [review]
Maybe you have to grep **IRC** inside `navitia/documentation`, too ?

**Comment by kinnou02** [comment]
> Maybe you have to grep **IRC** inside `navitia/documentation`, too ?

```
% rg -w 'irc' -l
readme.rst
documentation/slate/source/includes/welcome.md
```
Those are handled in #2972

**Review by nonifier — APPROVED** [review]
riot is the language of the unheard

**Review by pbougue — APPROVED** [review]
This can be managed step by step (as long as this is not a marathon).

**Pull request merged**
