### PR TITLE
kraken: contributor of trip.extension used in disruption for gtfs-rt

### PR DESCRIPTION
**Pull request by kadhikari**

### CODE REVIEW

**Review by pbougue — COMMENTED** [review]
Looks good, but we have to check how it will behave for SNCF, see if it changes the contributor (and if it used to be meaningfull): avoid breaking integrations that would filter on that (see if the question is real)

**Comment by pbougue** [comment]
Jenkins, test this please

**Comment by kadhikari** [comment]
A contributor is always present in 'IRE' while using KirinModelBuilder and a disruption always have a contributor associated in gtfs_realtime_pb2.

We can also differenciate a contributor associated to a disruption and a contributor (rt_topic ?) used to canalize disruptions in RabbitMQ...

**Comment by buildbotctp** [comment]
Build finished.

**Review by kinnou02 — APPROVED** [review]

**Review by TeXitoi — APPROVED** [review]

**Pull request merged**
