### PR TITLE
routing: mutualize CachedNextStopTimeManager between threads

### PR DESCRIPTION
**Pull request by TeXitoi**

### CODE REVIEW

**Comment by TeXitoi** [comment]
Jenkins skip this please

**Comment by antoine-de** [comment]
OK for me

**Comment by antoine-de** [comment]
waiting for stress bench

**Comment by pbougue** [comment]
Ok for me, maybe a new perf bench

**Comment by pbougue** [comment]
Stress bench OK, sequential perf not affected

**Pull request merged**
