### PR TITLE
Doc: fix print function

### PR DESCRIPTION
**Pull request by xlqian**

### CODE REVIEW

**Review by kinnou02 — APPROVED** [review]

**Comment by pbougue** [comment]
Maybe you can add the `__future__` imports then

**Comment by xlqian** [comment]
@pbougue you mean this line? https://github.com/CanalTP/navitia/pull/2369/files#diff-c5deef25497a79b0266d6ca574829ba8R30

**Comment by pbougue** [comment]
Yep :)
But... How come it worked before??

**Comment by xlqian** [comment]
@pbougue you can ask @TeXitoi who made the last release :)

**Comment by pbougue** [comment]
OK, turns out it didn't work, the last ones who used it used a workaround.
It's clear and it's fine :)

**Review by pbougue — APPROVED** [review]

**Review by TeXitoi — APPROVED** [review]

**Review by nonifier — APPROVED** [review]

**Pull request merged**
