### PR TITLE
Add requirements in cmake to help compilation preparation

### PR DESCRIPTION
**Pull request by guikcd**
- Use existing Findlog4cplus.cmake and silent detection if already correctly detected
- Silent Boost detection if correctly detected
- Detect protoc binary (throws an error if missing)
- Detect google/malloc_extension.h (throws an error if missing)
- Translate comments

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by antoine-de** [comment]
ok to test

**Comment by kinnou02** [comment]
Your holiday seems boring :p

**Comment by l-vincent-l** [comment]
he meant thank you!

**Pull request merged**
