### PR TITLE
Doc: fix default database name

### PR DESCRIPTION
**Pull request by thiphariel**
I think it's the only remaining problem with the build_navitia.sh script. But just in case, let me finish another install

[Review on Reviewable](https://reviewable.io/reviews/canaltp/navitia/1184)

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by pbougue** [comment]
Tagged it, now waiting for your feedback

**Comment by thiphariel** [comment]
Sorry for the delay, but I built it once from fresh clone and I do not encounter any issue. If it's good for you, you can merge

**Comment by pbougue** [comment]
Thanks for the contrib!

**Pull request merged**
