### PR TITLE
Revert "[Jormungandr] Use transient socket for instance, pt planner and asgard, AND remove socket reaper"

### PR DESCRIPTION
**Pull request by pbougue**
Reverts hove-io/navitia#3883

Just in case.

### CODE REVIEW

**Review by xlqian — APPROVED** [review]

**Comment by pbougue** [comment]
Rebased onto v15.26.0 to avoid embedding any other PR merged since.

**Comment by xlqian** [comment]
~Rebased onto v15.26.3, pre-release created v15.26.5.~

**Comment by xlqian** [comment]
Release v15.26.4

**Comment by pbougue** [comment]
After some tests and use without reverting, this revert should not be necessary, ever.

**Pull request closed without merging**
