### PR TITLE
Stay in fixes

### PR DESCRIPTION
**Pull request by koch-t**
Fixes SQL query error.
Fixes stay_in's where vehicle has more than 120 seconds between two interline sections.

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by koch-t** [comment]
My feeling is that the change in raptor_path is not the fix but covering the real bug. Why is the vehicle extension overruled by a non-direct Journey of equal lenght?

**Comment by koch-t** [comment]
ok to test

**Comment by antoine-de** [comment]
ok to test

**Comment by koch-t** [comment]
Now the reversal errors are taken care of in #431, i feel a little bit more comfortable about this PR

**Comment by l-vincent-l** [comment]
@skywave do you think we can merge this branch?
We know the problem is not on your branch but on #431 (and this branch is not mergeable yet, I haven't find why it's buggy).

**Comment by koch-t** [comment]
This branch is mergeable.

**Pull request merged**
