### PR TITLE
Fix 2nd pass bug

### PR DESCRIPTION
**Pull request by l-vincent-l**
There was a bug in the second pass with this.
Some journeys were not able to be compute. This solves it, but I can't really understand why it works.

### CODE REVIEW

**Comment by koch-t** [comment]
I think the common pattern between journeys that failed: journeys with the same departuretime (same trip in fact) but differing amount of transfers/travel-length.

**Comment by koch-t** [comment]
Should be closed after #478 ?

**Comment by l-vincent-l** [comment]
It might, i still have to do tests, i noticed strange behaviours

**Comment by antoine-de** [comment]
can you rebase it ?

Is it still up to date ?

**Comment by l-vincent-l** [comment]
it isn't I close it

**Pull request closed without merging**
