### PR TITLE
Refactor double negation away

### PR DESCRIPTION
**Pull request by koch-t**

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by l-vincent-l** [comment]
I think we need to rewrite the whole function.

Here we create stop_area only if this is a file without any stop_area, we want to create a stop_area for every stop_point without a stop_area.

**Comment by kinnou02** [comment]
ok to test.

**Comment by antoine-de** [comment]
I close this pull request, it has been handled by #322 
I don't understand why github does not close it automaticaly since the commit has been merged and the pull request closed in the #322 pullrequest message

**Pull request closed without merging**
