### PR TITLE
Coherence of objects in a node of two sections

### PR DESCRIPTION
**Pull request by kadhikari**
Concerned ticket: https://jira.kisio.org/browse/NAVP-981

### CODE REVIEW

**Review by TeXitoi — CHANGES_REQUESTED** [review]
We can't do that, It can break integrations by removing fields that where always present before.

**Comment by TeXitoi** [comment]
That's surprising that Alex asked for that.

**Review by pbougue — COMMENTED** [review]
Adding `do_not_merge` as we need to discuss what's needed it a bit with @kinnou02 , as I mentionned in JIRA.

**Comment by kinnou02** [comment]
There is no good choice here, let's say we don't do anything

**Pull request closed without merging**
