### PR TITLE
Route: add direction field.

### PR DESCRIPTION
**Pull request by aelkhour**
This PR is a proposal for issue #492.

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by antoine-de** [comment]
thanks for the patch @aelkhour !

**Comment by antoine-de** [comment]
jenkins, test this please

**Comment by antoine-de** [comment]
@aelkhour I think it's better for the 'direction' to be a complete object and not just a string.

I made a proposal about that on your PR (https://github.com/aelkhour/navitia/pull/1)

is it ok with you ?

This way a route will be displayed as:

``` json
 "route": {
        "direction": {
          "embedded_type": "stop_point", 
          "stop_point": {
         ...
          }, 
          "quality": 0, 
          "id": "stop2", 
          "name": "stop2 (paris)"
        }, 
        "is_frequence": "False", 
        "line": {
          ....
         }
...
}
```

**Comment by aelkhour** [comment]
@antoine-de Fine with me, I think it's a good idea.

**Comment by antoine-de** [comment]
thanks!

damn, I did not realize that the branch was not mergeable with dev.

could you rebase it with dev ? (I did it on  [my branch](https://github.com/antoine-de/navitia/tree/route-direction) but then it cannot be merged with yours :smile: )

**Comment by aelkhour** [comment]
Rebased on dev.

**Comment by antoine-de** [comment]
thanks for the patch @aelkhour !

**Comment by aelkhour** [comment]
Thanks for the merge @antoine-de :-)
Quick question: generally speaking, how long after a deliverty on dev should we wait until it is available on the navitia.io api?

**Comment by antoine-de** [comment]
It's a bit long, we just delivered the patch on our internal platform. Some testing needs to be done and I think it will be delivered on navitia.io beginning of October.

**Pull request merged**
