### PR TITLE
test jenkins

### PR DESCRIPTION
**Pull request by buildbotctp**
test pull request in jenkins

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by antoine-de** [comment]
test this please

**Comment by l-vincent-l** [comment]
Le ven. 14 mars 2014 15:23:04 CET, Antoine D a écrit :

> test this please
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CanalTP/kraken/pull/200#issuecomment-37651806.

hummmmm

**Comment by antoine-de** [comment]
test this please

**Comment by antoine-de** [comment]
test this please

**Comment by antoine-de** [comment]
test this please

**Comment by antoine-de** [comment]
test this please

**Pull request closed without merging**
