### PR TITLE
Swagger: fix properties schema

### PR DESCRIPTION
**Pull request by xlqian**
https://jira.kisio.org/browse/NAVITIAII-2580

### CODE REVIEW

**Comment by xlqian** [comment]
jenkins, test this please!

**Review by benoit-bst — APPROVED** [review]
easy win

**Review by kadhikari — APPROVED** [review]
It's very difficult to detect error between shema and response json using validator.

**Review by pbougue — APPROVED** [review]
This kind of error should be detected with #2564 who would check at every depth-level of the swagger.

**Review by TeXitoi — APPROVED** [review]

**Pull request merged**
