### PR TITLE
Experimental: fix direct path key not found in the pool

### PR DESCRIPTION
**Pull request by xlqian**
experimental crashed when departure mode and arrival mode are different

### CODE REVIEW

**Comment by TeXitoi** [comment]
Unit test ?

**Comment by xlqian** [comment]
Note:

The test that i added **didn't** pass on `dev`

**Review by TeXitoi — APPROVED** [review]

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by TeXitoi** [comment]
Jenkins, test this please

**Pull request merged**
