### PR TITLE
Fix one cause for segfault for trains w/ midnight departure

### PR DESCRIPTION
**Pull request by koch-t**
It fixes some segfault's but not all.

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by koch-t** [comment]
Without this patch Navitia is unable to find stop_time's with a departure_time of 24:00:00 and trigger segfaults in some scenario's.

But with this patch Navitia triggers another bug causing segfaults which would previously result in just a "No solutions found" error.

**Comment by antoine-de** [comment]
We are refactoring this part, so I think we'll integrate your patch in a bigger pull request.

**Comment by antoine-de** [comment]
ok to test

**Comment by l-vincent-l** [comment]
Can you send the request causing the segfault with this PR?

**Comment by koch-t** [comment]
stop_area:alm to stop_area:asd departure after 20140506T0000 

http://api.navitia.io/v1/journeys?from=stop_area:OAM:SA:17827&to=stop_area:OAM:SA:18188&datetime=20140506T000000
http://localhost:5000/v1/journeys?from=stop_area:alm&to=stop_area:asd&datetime=20140506T000000

Should give the train
(stop_area:alm, arrives at 23:59 departs at 24:01) -> (stop_area:asd, arrives at 24:24:00)

The biggest problem is that it does work on the smaller train-dataset.

**Comment by l-vincent-l** [comment]
Fixed by #331

**Pull request closed without merging**
