### PR TITLE
Revert "[Kraken]: use Flann to find nearest objects"

### PR DESCRIPTION
**Pull request by xlqian**
Reverts CanalTP/navitia#2774

### CODE REVIEW

**Review by kinnou02 — APPROVED** [review]

**Review by pbougue — APPROVED** [review]
Trusting you and github on the revert ;)

**Comment by xlqian** [comment]
in case of disater :hankey: , plz blame github, not me, :man_shrugging:

**Comment by kinnou02** [comment]
Jenkins, test this please.

**Review by benoit-bst — APPROVED** [review]
Bye Flann, you were a good one

**Pull request merged**
