### PR TITLE
[Utils] bump utils commit to use new zmq.cpp

### PR DESCRIPTION
**Pull request by xlqian**
https://github.com/CanalTP/utils/pull/90

### CODE REVIEW

**Review by AurelienLP — APPROVED** [review]

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by xlqian** [comment]
Jenkins failed because of using copy constructor(A move constructor was actually used, but older version doesn't have move constructor...)

https://github.com/zeromq/zeromq2-x/blob/19a5e9ac843eecb2e9ea0b8e6380cd67428e5a3d/include/zmq.hpp

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by xlqian** [comment]
Jenkins, test this please!

**Pull request closed without merging**
