### PR TITLE
access point: conceal length and traversal time

### PR DESCRIPTION
**Pull request by benoit-bst**

### CODE REVIEW

**Review by kadhikari — APPROVED** [review]

**Comment by kadhikari** [comment]
We didn't have any integration test to verify attributes length and traversal_time ??

**Review by kadhikari — CHANGES_REQUESTED** [review]
Modify tests on traversal_time and length

**Comment by benoit-bst** [comment]
off course we have :heart:

**Comment by benoit-bst** [comment]
off course we have :heart:

**Review by pbench — APPROVED** [review]

**Review by xlqian — APPROVED** [review]

**Pull request merged**
