### PR TITLE
Delete user email in release changelog

### PR DESCRIPTION
**Pull request by kadhikari**
For details: https://jira.kisio.org/browse/NAVITIAII-3341

### CODE REVIEW

**Review by benoit-bst — COMMENTED** [review]
I am not sure about that.
I think It will not work, because debian package need an Author. Maybe a name like Navitia and a generic email will be better.

**Comment by kadhikari** [comment]
I don't see any use of email apart writing name + email + ... in a line. I don't understand "debian package need an Author"

"Maybe a name like Navitia and a generic email will be better" -> good Idea

**Comment by xlqian** [comment]
and our organization email will still stand in previous commits...

**Comment by benoit-bst** [comment]
In any case, the **github** **history**  exposes our mail... This is only for the future

**Comment by kadhikari** [comment]
Email address will not be deleted. The user is suggested to use his/her company's email address.

**Pull request closed without merging**
