### PR TITLE
Swagger: fix car_park swagger

### PR DESCRIPTION
**Pull request by xlqian**
https://jira.kisio.org/browse/NAVITIAII-2575

### CODE REVIEW

**Review by pbougue — APPROVED** [review]

**Comment by xlqian** [comment]
There'll be a second PR to do testing stuff...

**Review by nonifier — APPROVED** [review]

**Comment by nonifier** [comment]
retest this please

**Review by kadhikari — APPROVED** [review]

**Comment by xlqian** [comment]
jenkins test this please!

**Comment by xlqian** [comment]
Jenkins, test this please!

**Pull request merged**
