### PR TITLE
Ed: fix timezone generation

### PR DESCRIPTION
**Pull request by antoine-de**
The timezones could be unaligned with the production period (when the
production period had been shifted due to pass midnight :wink: )

the resulting problem was a internal error saying 'no intersection with
a timezone found'

[Review on Reviewable](https://reviewable.io/reviews/canaltp/navitia/1410)

### CODE REVIEW

**Comment by xlqian** [comment]
_[a discussion](https://reviewable.io:443/reviews/canaltp/navitia/1410#-KAElwPc9mu67UNgaEBF:-KAElwPc9mu67UNgaEBG:1631476015) (no related file):_
can we have some functional tests for the fix?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canaltp/navitia/1410)_

**Comment by xlqian** [comment]
_[source/ed/data.cpp, line 811 [r1]](https://reviewable.io:443/reviews/canaltp/navitia/1410#-KAEsfoUyjtVgcJgeyEt:-KAEsfoUyjtVgcJgeyEu:-738892929) ([raw file](https://github.com/canaltp/navitia/blob/b9065253519c96ee265093d0fb4368e1a03014c1/source/ed/data.cpp#L811)):_
not sure whether you need this test...

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canaltp/navitia/1410)_

**Comment by xlqian** [comment]
Reviewed 3 of 10 files at r1.
Review status: 3 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canaltp/navitia/1410)_

**Comment by xlqian** [comment]
Reviewed 7 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canaltp/navitia/1410)_

**Comment by antoine-de** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/canaltp/navitia/1410#-KAElwPc9mu67UNgaEBF:-KAEwOQh6iY34-putKwp:1743915322) (no related file):_
I don't know how to do it :(

---

_[source/ed/data.cpp, line 811 [r1]](https://reviewable.io:443/reviews/canaltp/navitia/1410#-KAEsfoUyjtVgcJgeyEt:-KAEwAjU-akgGfWH2__F:335147196) ([raw file](https://github.com/canaltp/navitia/blob/b9065253519c96ee265093d0fb4368e1a03014c1/source/ed/data.cpp#L811)):_
I think it's needed, the dst periods span over several years

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canaltp/navitia/1410)_

**Comment by xlqian** [comment]
ok for me

**Pull request merged**
