### PR TITLE
CI: fill releases field with release ga job

### PR DESCRIPTION
**Pull request by benoit-bst**
like -> https://github.com/CanalTP/core_team_ci_tools
or -> https://github.com/CanalTP/transit_model

Doc : ~~https://github.com/actions/create-release~~ -> https://github.com/softprops/action-gh-release

### CODE REVIEW

**Review by pbench — APPROVED** [review]
Nice ! 
If I understand correctly, when something with a tag is pushed, this creates a release in github (like https://github.com/CanalTP/core_team_ci_tools/releases/tag/v.0.9.2)  containing the source code.
Could we also upload the debian packages of navitia into the release ?
Little caveat : the readme of [actions/create-release](https://github.com/actions/create-release) states that this repo is unmaintained.

**Review by azime — APPROVED** [review]

**Comment by benoit-bst** [comment]
> Nice !
>If I understand correctly, when something with a tag is pushed, this creates a release in >github (like https://github.com/CanalTP/core_team_ci_tools/releases/tag/v.0.9.2) >containing the source code.
>Could we also upload the debian packages of navitia into the release ?
>Little caveat : the readme of actions/create-release states that this repo is unmaintained.
 
Okay @pbench you think about that https://github.com/actions/upload-release-asset
I can try

**Comment by pbench** [comment]
> Okay @pbench you think about that https://github.com/actions/upload-release-asset
Yes exactly ! 
> I can try
Thanks :+1:

**Comment by benoit-bst** [comment]
@pbench what do you think about https://github.com/softprops/action-gh-release ?
I don't know what is the official action...

**Comment by pbench** [comment]
> @pbench what do you think about https://github.com/softprops/action-gh-release ?

The documentation looks good ! 

> I don't know what is the official action...

I have no idea either... As long as it works it's fine for me. 
I guess these actions will keep working until github decides to change its api.

**Review by pbench — APPROVED** [review]

**Pull request merged**
