### PR TITLE
kraken: fix compilation on debian7

### PR DESCRIPTION
**Pull request by TeXitoi**

### CODE REVIEW

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Je

**Comment by TeXitoi** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Jenkins, test this please

**Pull request merged**
