### PR TITLE
Jormun: default conf for max count value

### PR DESCRIPTION
**Pull request by sign0**
Added
- PARSER_MAX_COUNT=1000

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Review by antoine-de — APPROVED** [review]

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by kinnou02** [comment]
ok to test

**Pull request merged**
