### PR TITLE
jormun & tyr: fix problem caused by pip 10.0.0

### PR DESCRIPTION
**Pull request by xlqian**
https://github.com/pypa/pip/issues/5271
https://github.com/pypa/pip/issues/5251

### CODE REVIEW

**Comment by TeXitoi** [comment]
Jenkins test this please

**Comment by mbounabi** [comment]
Jenkins, test this please

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by pbougue** [comment]
To be tested manually the same way deployment is done on prod platform

**Comment by kadhikari** [comment]
jenkins test this please

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by xlqian** [comment]
@kinnou02  I've built *.deb with this PR(https://ci.navitia.io/job/navitia_dev-clone_test_xl/7/) and succeeded in deploying them on alpha(https://ci.navitia.io/job/deploy_navitia_on_alpha/1406/console). Note that alpha's pip version is still 8.1.1 which is the same as on  prod

**Review by nonifier — APPROVED** [review]

**Review by kinnou02 — APPROVED** [review]

**Pull request merged**
