### PR TITLE
Jormungandr: use simplejson, it's supposed to be faster

### PR DESCRIPTION
**Pull request by l-vincent-l**

### CODE REVIEW

**Comment by TeXitoi** [comment]
We wait our benchmark platform to merge that.

**Comment by antoine-de** [comment]
seems to improve by 1-2% the overall bench

**Comment by l-vincent-l** [comment]
http://permalink.gmane.org/gmane.comp.db.sqlite.general/90549

The 50% faster number above is not about better query plans.  This is 50%
faster at the low-level grunt work of moving bits on and off disk and
search b-trees.  We have achieved this by incorporating hundreds of
micro-optimizations.  Each micro-optimization might improve the performance
by as little as 0.05%.

**Comment by antoine-de** [comment]
:)

I need to test ultra json too, to see if it changes something

**Pull request merged**
