### PR TITLE
jormun: remove geojson from stop_schedule too!

### PR DESCRIPTION
**Pull request by kinnou02**

### CODE REVIEW

**Review by pbougue — APPROVED** [review]
Ok for me. Maybe we should just do it everywhere, no?
How about some doc in the same PR? Would be niiiice :)

**Comment by TeXitoi** [comment]
Yeah, and particularly on coverage.

**Review by pbougue — CHANGES_REQUESTED** [review]
Can we add some doc?
(To test this feature also)

**Review by TeXitoi — COMMENTED** [review]
Could be great:
- support this on autocomplete (pt_objects and places)
- support this on coverage

**Review by pbougue — APPROVED** [review]

**Pull request merged**
